[book]
title = "Ordinal Theory Handbook"
language = "en"
src = "src"

[build]
build-dir = "build"
create-missing = false

[output.html]
cname = " "
default-theme = "coal"
git-repository-url = "https://github.com/DrJingLee/OrdinalsDocs"
preferred-dark-theme = "coal"

[output.linkcheck]
